apiVersion: v1
kind: Secret
metadata:
  name: travel-tours-backend-secret
  namespace: travel-tours
type: Opaque
stringData:
  POSTGRES_USERNAME: travel_tours
  POSTGRES_PASSWORD: travel_tours
  JWT_SECRET_KEY: 7ac51f34954d17b2c22a1a95ea44f1f61c72a0b87d186c8e2c607edb4db99ffd
