apiVersion: v1
kind: Service
metadata:
  name: travel-tours-backend
  namespace: travel-tours
spec:
  type: ClusterIP
  selector:
    app: travel-tours-backend
  ports:
    - port: 8080
      targetPort: 8080
      name: http