apiVersion: v1
kind: Secret
metadata:
  name: travel-tours-db-secret
  namespace: travel-tours
type: Opaque
stringData:
  POSTGRES_USER: travel_tours
  POSTGRES_PASSWORD: travel_tours
  POSTGRES_DB: travel_tours